# Use the official NGinx image from the Docker Hub
FROM nginx:latest

# Copy the contents of the public folder to the appropriate location in the NGinx container
COPY public /usr/share/nginx/html

# Expose port 80 to access the container
EXPOSE 80