services:
  db:
    image: mariadb:latest
    container_name: challenge4-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - challenge4-network

  node-service:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: mydatabase
    networks:
      - challenge4-network
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: challenge4-nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service
    networks:
      - challenge4-network

volumes:
  db_data:

networks:
  challenge4-network:
